### ISSUE TITLE
Rebels MC lvl 1 rewards

### ISSUE THREAD

**Issue by Kare0015** [saesrpg/saesrpg-web#10]
We'd like to request our private forums (gang lvl 1 reward). 
The vehicles are already sorted.

Felix owner, bas moderation rights please.

Link to our old request of december the 2nd: 
https://oldbugs.saesrpg.uk/view.php?id=825

**Comment by FilexGH** [comment]
**Felix Account** : https://saesrpg.uk/user/felix
**Bas Account** : https://saesrpg.uk/user/bas
