### ISSUE TITLE
SF Forums 

### ISSUE THREAD

**Issue by Marko201** [saesrpg/saesrpg-web#102]
requesting view access on Special Forces [forums](https://saesrpg.uk/category/74/desert-eagles) 

https://saesrpg.uk/user/marko

**Comment by DemienD** [comment]
Permission confirmed

**Comment by SAESBunny** [comment]
Permission confirmed

**Comment by DemienD** [comment]
Confirmation is strong on this one

**Comment by Scorpyooooo** [comment]
Very strong

**Comment by CrashSystem** [comment]
Permission Granted
