### ISSUE TITLE
Edit history enhancement

### ISSUE THREAD

**Issue by boney420** [saesrpg/saesrpg-web#103]
a topic which is maintained by serval people shows no edit-author in the dropdown list
Would be moist if we could see who has edited what :dancing_women: 
If possible even highlight the edits :D

Edit log only shows a username upon most recent edit
https://i.imgur.com/hobAcSs.png

Elder edits are listed without username.
https://i.imgur.com/MZycmZb.png

**Comment by saesrpg** [comment]
Try requesting it on the NodeBB github, its not a 'template' thing we can add.
