### ISSUE TITLE
Changing the password in forum small bug

### ISSUE THREAD

**Issue by Garcia1999** [saesrpg/saesrpg-web#112]
Hello everyone 

When you write your current password **wrong** (to change your password)
and you write a new password, it says : **The password entered is too short, please pick a different password.**
even if your new password is as long as teddy's retardness

And if you write your current password **Right** its normaly change.

the point in that is: change the (**The password entered is too short, please pick a different password.**) to (**Your current password is wrong**)

**Comment by saesrpg** [comment]
Passwords need to be a minimum of 6 characters
