### ISSUE TITLE
IAC private forum rights

### ISSUE THREAD

**Issue by Kim01900** [saesrpg/saesrpg-web#113]
Greetings,
I had recently requested forums moderator rights for InvestArms Corporation (IAC). However, I did not receive all the options, these are not necessary enough as the group's new leader. Therefore I'd be grateful if any of you can fix that and provide me full administrator, i.e. permissions such as to delete/edit, etc. that includes subcategories too.

Link to IAC Forums - https://saesrpg.uk/category/107/investarms-corporation

**Comment by saesrpg** [comment]
This is now done @Kim01900
