### ISSUE TITLE
Lounge INC. Admin Permissions

### ISSUE THREAD

**Issue by Markus139** [saesrpg/saesrpg-web#116]
Hello,

Recently Lounge has got more active and stuff. I'd like to request full administrative access to both of these accounts so we can lock, move the topic and all of that.

**Proof:**
https://gyazo.com/9e108a0392f10bdf8ec87ea4cbc4d52d
https://gyazo.com/b43be22110e6c8b838be57264b37aad8
https://gyazo.com/1f0ce0b6d780d64eb2d848d6c718593d

_nobodyLovesMe is Assassin_. 

**What accounts should be given the permissions?:**
https://saesrpg.uk/user/markus
https://saesrpg.uk/user/lounge-vc
https://saesrpg.uk/user/assassin

**ALSO! Change the name Lounge INC. to Lounge VC**
https://saesrpg.uk/category/137/lounge-inc

Thanks.

**Comment by saesrpg** [comment]
This is now done @Markus139
