### ISSUE TITLE
Lounge VC HQ Subforums

### ISSUE THREAD

**Issue by Markus139** [saesrpg/saesrpg-web#118]
Could we get an HQ Subforum & an Archive subforum where we can move stuff?

https://saesrpg.uk/category/137/lounge-vc

 **ONLY ACCESSIBLE BY HQS PLEASE**

**Comment by saesrpg** [comment]
@Markus139 who are your HQ?

Please list the forum accounts here.

**Comment by Markus139** [comment]
Nirjhor & Tuned are missing. Remove Toreno @saesrpg

**Comment by saesrpg** [comment]
This is now done.
