### ISSUE TITLE
FBI sub-forums

### ISSUE THREAD

**Issue by pothead74** [saesrpg/saesrpg-web#119]
Since it's now allowed to have your own gang/squad sub-forum,
We'd like to have one under the name of ' Federal Bureau Of Investigation'
Description : Federals nest

Mod access goes to : https://saesrpg.uk/user/potato
https://saesrpg.uk/user/ramos

Cheers.

**Comment by saesrpg** [comment]
This is now done.

I have created the private subforum, moved all your topics there and I've opened your main forum to the public

Next time, also tag any media and recruitment topics you want moving there for you to self moderate.
