### ISSUE TITLE
ICE Sub-Forums

### ISSUE THREAD

**Issue by 00Sam00** [saesrpg/saesrpg-web#121]
We'd like to to request a sub-forum for ICE.

Name: Immigration and Customs Enforcement's

Please move the following topic to the sub-forum: 
https://saesrpg.uk/topic/138/ice-immigration-customs-enforcement
https://saesrpg.uk/topic/16/ice-immigration-customs-enforcement-media-archive

We also want to keep our Private Forum Topics. [Spoken to brophy about this]

Moderator access goes to : 
https://saesrpg.uk/user/sam
https://saesrpg.uk/user/james

**Comment by saesrpg** [comment]
This is now done
