### ISSUE TITLE
ETF Sub Forum

### ISSUE THREAD

**Issue by Vennelle** [saesrpg/saesrpg-web#122]
Hello! 

We would like to have the ETF main topic and Media archive in 1 sub forum.

Media archive: https://saesrpg.uk/topic/9253/etf-emergency-task-force-media-archive

Main topic: https://saesrpg.uk/topic/9251/etf-emergency-task-force

With the name: Emergency Task Force

And mod acces to: https://saesrpg.uk/user/vennelle & https://saesrpg.uk/user/antirug

Thank you!

**Comment by saesrpg** [comment]
This is now done.
