### ISSUE TITLE
Undisputed Command Sub Forum

### ISSUE THREAD

**Issue by stayA9** [saesrpg/saesrpg-web#123]
Hello!

We would like to have the Undisputed Command main topic and Media archive in 1 sub forum, 

Media archive: https://saesrpg.uk/topic/11233/undisputed-command-media-archive

Main topic: https://saesrpg.uk/topic/11232/undisputed-command-level-1

With the name: Undisputed Command

And mod acces to https://saesrpg.uk/user/stay / https://saesrpg.uk/user/venom / https://saesrpg.uk/user/douglass

Thank you!

**Comment by saesrpg** [comment]
This is now done.
