### ISSUE TITLE
Vándalos de El Corona subforum

### ISSUE THREAD

**Issue by SAESHenry** [saesrpg/saesrpg-web#124]
Hello, we'd like to have a subforum linked to our gang forum group with the name of our gang "Vándalos de El Corona" https://saesrpg.uk/groups/v%C3%A1ndalos-de-el-corona that includes the following topics:

- **Application topic:** https://saesrpg.uk/topic/9416/v%C3%A1ndalos-de-el-corona?page=1

- **Media archive:** https://saesrpg.uk/topic/9418/v%C3%A1ndalos-de-el-corona-media-archive/347

To be moderated by the role of "group owner" or incase it requires profiles, these 3:

- https://saesrpg.uk/user/henry

- https://saesrpg.uk/user/ccc

- https://saesrpg.uk/user/ronnie

Thanks!

**Comment by saesrpg** [comment]
This is now done.
