### ISSUE TITLE
Los Escondidos forum request

### ISSUE THREAD

**Issue by L1nkan** [saesrpg/saesrpg-web#125]
Yo, as Brophy earlier today announced we can have a total of 2 Sub-forums for each gang. I would like to have one more for Los Escondidos. We would like to have the current one (https://saesrpg.uk/category/365/los-escondidos ) for public. Then we would like to add a second forum in our public one named "Los Escondidos Members" 

**Move these topics to the public one** 
https://saesrpg.uk/topic/11897/los-escondidos/142
https://saesrpg.uk/topic/11898/los-escondidos-media-archive?page=1

**Move these topics to our new Private one**
https://saesrpg.uk/topic/12889/los-escondidos-suggestions
https://saesrpg.uk/topic/12756/los-escondidos-general-chat/32
https://saesrpg.uk/topic/12785/los-escondidos-blacklist
https://saesrpg.uk/topic/12776/los-escondidos-inactivity-topic
https://saesrpg.uk/topic/12757/los-escondidos-recruitment-voting/13
https://saesrpg.uk/topic/12864/los-escondidos-blackhole/7

Please keep Homeless buly topic in the public one thanks.

**Forum Admin**
remove "Simon" from the forum moderation ( https://saesrpg.uk/user/sim0nn93 ) the Los Esondidos one, he shall not have acces to any of them

Add Me ( https://saesrpg.uk/user/linkan ) To New one aka Private
Add Sweman ( https://saesrpg.uk/user/sweman ) to new one aka Private
Also add Twenta ( https://saesrpg.uk/user/twenta ) to the public one (Los Esondidos)

**Comment by saesrpg** [comment]
This is now done.
