### ISSUE TITLE
Five-0 Forums Update

### ISSUE THREAD

**Issue by TheMetalizer** [saesrpg/saesrpg-web#126]
Greetings,

I'd like to request a public forum section for Five-0, following topics should be moved there:

1) https://saesrpg.uk/topic/10850/san-andreas-five-0
2) https://saesrpg.uk/topic/10851/five-0-media-archive

Moderators for this new section should be: Terry, Ramby & ElRastaMan17

**Comment by saesrpg** [comment]
This is now done.
