### ISSUE TITLE
AA Forums update.

### ISSUE THREAD

**Issue by Ahren7413** [saesrpg/saesrpg-web#127]
Hello there! According to the new way of organizing and moderating the new gang/squads sub forums, we'd like to request it to be implemented in an Arms Assassins subforums.

These would be the threads that should be added in the public subforum: 

- https://saesrpg.uk/topic/486/arms-assassins-media-archive/529
- https://saesrpg.uk/topic/602/arms-assassins/345

The moderations right for this section should be: 

- Illusion (https://saesrpg.uk/user/illusion)
- Yoko_Kurama (https://saesrpg.uk/user/yoko_kurama)
- Licano (https://saesrpg.uk/user/licano)
- Ikzelf (https://saesrpg.uk/user/ikzelf)
- nicus (https://saesrpg.uk/user/nicus)
- Canelas (https://saesrpg.uk/user/canelas)

Don't know if worth mentioning but we'd also like the current threads in the  private forums (https://saesrpg.uk/category/40/arms-assassins) to be moved towards the new private section mentioned in the announcement. 

Thank you in advance.

**Comment by saesrpg** [comment]
This is now done.
