### ISSUE TITLE
TT forum update

### ISSUE THREAD

**Issue by GrooveOG** [saesrpg/saesrpg-web#128]
Hello there! According to the new way of organizing and moderating the new gang/squads sub forums, we'd like to request it to be implemented in a Tuga Thugs subforum. (ty licano!!)

We would like to have these 2 topics moved on our subcategory:

- https://saesrpg.uk/topic/37/tuga-thugs
- https://saesrpg.uk/topic/652/tugathugs-media-archive

From there, we would like to have the following sub-subcategory:

- a category named "Tuga Thugs private forum". If possible, move all the forum on our current private forum there.

(If it's possible to have moving rights within that section, we would like to have two archive section: one for the tuga thugs subcategory, and one for the private forum; a bit like this: https://i.imgur.com/nA0Yjtb.png . If it's not possible, ignore what was mentioned on the previous sentence)

The following people should have admin rights:

- Jokila: https://saesrpg.uk/user/jokilapt
- Groove: https://saesrpg.uk/user/groove
- Zwolle: https://saesrpg.uk/user/zwolle
- Tritosh: https://saesrpg.uk/user/tritosh
- Note: https://saesrpg.uk/user/note
- blizzard: https://saesrpg.uk/user/blizzard

**Comment by saesrpg** [comment]
This is now done.

**Comment by Colobria** [comment]
Admin rights
Colobria: https://saesrpg.uk/user/colo
• https://saesrpg.uk/topic/37/tuga-thugs
• https://saesrpg.uk/topic/652/tugathugs-media-archive
