### ISSUE TITLE
Administrative access for Markus

### ISSUE THREAD

**Issue by Markus139** [saesrpg/saesrpg-web#133]
Hey!

As I recently became HQ in SAI, Administrative access was allowed for me to request. I'd like the thingy where I can lock, move topics, etc

Proof:
https://gyazo.com/f20129f6045f97badd61c94b421c0fb5

Admin access for the following account:
https://saesrpg.uk/user/markus

**Comment by SAESHenry** [comment]
Approved by SAI HQ

**Comment by boney420** [comment]
resolved.
