### ISSUE TITLE
TMH forum moderators and HQ forum viewing rights changes.

### ISSUE THREAD

**Issue by taj125** [saesrpg/saesrpg-web#145]
Hello there!
I'd like to request a few changes on [TMH Forums](https://saesrpg.uk/category/173/the-motor-heads-tmh).

Forums Moderators - TaJ, Reggi, Chemist and Hoodie (hoodie is the new addition).
HQ Forums viewing rights - The above moderators^, and KARIM, Brooks, mimyy, Xtream, Griffin, Pump, Filex, Beckham, Reacher.

Anyone else may be removed. For queries, I can be contacted at Discord almost any time except midnight. Thanks in advance! 

<details>
  <summary>Side note</summary>

  ```
  (Stop talking down below tounsis. Fine, removed you. But unblock me scorpyo thnx.)
  ```
</details>

**Comment by Scorpyooooo** [comment]
No not me

**Comment by FilexGH** [comment]
No NoT mE, iM rEmOvEd
