### ISSUE TITLE
GXT Forum Changes

### ISSUE THREAD

**Issue by Ramos116** [saesrpg/saesrpg-web#146]
Hi :)

Instead of subcategory name '' Global Express Trucking Company Private '', please change it to GXT Private.

Then, I'd also like to add beside this category, 2 more categories. Name them:
- GXT Applications (And inside GXT Applications section, I'd like to have subcategory named '' GXT Applications Archive'' ) (so it should be like this: https://prnt.sc/qhlmvx  / and only visible to moderators or group owners)
- GXT HQ

I want GXT HQ restricted to group owners only, if that's how it works.
I want GXT Applications to be visible to everyone.
So, in total, we have 3 cubcategories.

Now, if we move to private forums section:
Then in private forums, I wanna add 2 subcategories, named:
- Trucking Division
- Mechanical Division

**Comment by Ramos116** [comment]
and i'm not sure why can't i move topics to the top or the bottom, let me be able to do that in public and private section, because i cannot do that at the moment.

**Comment by Ramos116** [comment]
And moderator rights to me.

**Comment by Ramos116** [comment]
And please add, our logo pic here. ( https://prnt.sc/qgfqn1 )

Logo: https://imgur.com/a/EZxdf9E

**Comment by saesrpg** [comment]
This is now done @Ramos116 however you have plenty of forums already, therefore I've not added the division ones in private at this time.
