### ISSUE TITLE
Rebels forum update

### ISSUE THREAD

**Issue by NotFunni** [saesrpg/saesrpg-web#149]
Hello, I'd like to request the new subforum moderation thing that was announced some time back.

We'd like these 4 topics moved to the subforum:
https://saesrpg.uk/topic/9161/rebels-mc-level-3
https://saesrpg.uk/topic/3237/rebels-mc-media-archive?page=1
https://saesrpg.uk/category/275/rebels
https://saesrpg.uk/category/391/rebels-hq

Users that should be given moderation rights:
https://saesrpg.uk/user/bas
https://saesrpg.uk/user/jasper
https://saesrpg.uk/user/bagetto

**Comment by saesrpg** [comment]
This is now done @NotFunni
