### ISSUE TITLE
CC forum moderation

### ISSUE THREAD

**Issue by jaspermta** [saesrpg/saesrpg-web#151]
Oi,

It's been a while since we had our forum moderation sorted properly so here I am.
Could you remove everyone from the Cuban Cars forum moderation and add the following users:

Jasper - https://saesrpg.uk/user/jasper
Kristiina - https://saesrpg.uk/user/kristiina
Darius - https://saesrpg.uk/user/darius
Meister - https://saesrpg.uk/user/meister
Nico - https://saesrpg.uk/user/nico
Ardron - https://saesrpg.uk/user/ardron
Kipt - https://saesrpg.uk/user/kipt
N0vis0ry - https://saesrpg.uk/user/n0vis0ry

Thanks in advance.

**Comment by saesrpg** [comment]
This is now done @jaspermta
