### ISSUE TITLE
DE Forums

### ISSUE THREAD

**Issue by IG8820** [saesrpg/saesrpg-web#152]
Following sub-forums in the DE forum area to be renamed (https://saesrpg.uk/category/74/desert-eagles):
Airborne Unit -> Air Force
Assault Unit -> Army
Naval Unit -> Navy
Special Forces Unit -> Special Operations Command

I'd also like to request moderation for myself for all DE forums/ DE sub-forum areas. SAES>Patrol can be contacted in order to verify this request.

https://saesrpg.uk/user/ig8820

**Comment by saesrpg** [comment]
This is now done @IG8820
