### ISSUE TITLE
Izanagi Clan Private Forums and Group Request

### ISSUE THREAD

**Issue by Exiletemp** [saesrpg/saesrpg-web#154]
Hey!

I'd like to request private forums & a forum group for the Izanagi Clan
Our color code : #3AE0CB (if needed for creation of the forum group)
We've been approved for these rewards by the Group Managers, Jay and Daryl.

Please add 'Group Owner' to (https://saesrpg.uk/user/exile)
And give admin rights (lock, move etc) to these people
https://saesrpg.uk/user/markus
https://saesrpg.uk/user/exile
https://saesrpg.uk/user/dbmoodyblues
https://saesrpg.uk/user/avengēr
https://saesrpg.uk/user/hotfire
https://saesrpg.uk/user/kybali0n

We'd like a public sub-category under the groups section called "Izanagi Clan"

In this section we like to have these two topics visible to everyone:

https://saesrpg.uk/topic/10729/izanagi-clan-media-archive

https://saesrpg.uk/topic/10706/izanagi-clan

We'd also like 2 sub-forums within this section

Izanagi Clan Members (only accessible to people who are inside the forum group)
Izanagi Clan HQ (only accessible to people people with admin rights)

Please add our logo pic forum also - https://i.imgur.com/RplSktI.png

Proof of rewards being granted: https://imgur.com/a/Evb4Jpk

Thanks!

**Comment by saesrpg** [comment]
This is now done @Exiletemp
