### ISSUE TITLE
IAC ATM and forum Permissions

### ISSUE THREAD

**Issue by Kim01900** [saesrpg/saesrpg-web#155]
Hello as the title says, on behalf of IAC HQ, we request an ATM in our new base located in Red County
***
Also i would like to request admin permissions for Paradox
Link to his profile : https://saesrpg.uk/user/paradox
***
We would like to request 1 more subcategory into IAC Forums, ty :)

**Comment by SAESKain** [comment]
Not the place for ATM requests.

Paradox added.

Generally you have to tell us what you want the subforum naming when you want one.
