### ISSUE TITLE
BES Forum Admin permissions

### ISSUE THREAD

**Issue by Kim01900** [saesrpg/saesrpg-web#164]
Hello, i would like to get admin permissions such as lock,move,pin to all subcategories and categories, unless the previous leader (Virus) has retired from SAES, and he gave me leadership for BES.
Profile : https://saesrpg.uk/user/kim
***
Would you like to hide this subcategory only for BES members and HQs :
https://saesrpg.uk/category/156/application-archive-area

**Comment by saesrpg** [comment]
This is now done @Kim01900
