### ISSUE TITLE
SAPA application section moderator update

### ISSUE THREAD

**Issue by tutgreco** [saesrpg/saesrpg-web#167]
Hi, I would like [Qweezy](https://saesrpg.uk/user/qweezy) to receive the basic moderator permissions for the following section:
https://saesrpg.uk/category/184/sapa-application-section

If not done already I'd appreciate if Ramby could be removed.

**Comment by saesrpg** [comment]
This is now done @tutgreco

**Comment by tutgreco** [comment]
Thanks again 👍
