### ISSUE TITLE
Al Munazama Mod Permissions

### ISSUE THREAD

**Issue by Kim01900** [saesrpg/saesrpg-web#177]
Hello, that's me again..So, i would like to request full permissions for Al munazama, i demand tools such as delete,pin,move and lock, Thats the list of subcategories i should get permissions

 * https://saesrpg.uk/category/308/rebels-hideout
* https://saesrpg.uk/category/309/recruitment
* https://saesrpg.uk/category/310/al-munazama-application-archive

SAES profile : https://saesrpg.uk/user/kim

**Comment by SAESKain** [comment]
Done but perhaps lose the trash attitude in your next request or I'll just close it.
