### ISSUE TITLE
[E-mail Issue] Forum e-mail confirmation / Forgotten password recovery do not work

### ISSUE THREAD

**Issue by XgangsterX** [saesrpg/saesrpg-web#18]
Hi there,

I've seen people talking about not getting e-mail confirmations or that they can't change their lost password on the forums because they do not receive anything.

Is there by chance a problem or when there is time it can be looked at? This will resolve the people coming to discord to ask for activation, lost password recovery etc.

Greetings,

XgangsterX

**Comment by saesrpg** [comment]
Our mail provider has assigned us a new IP to try and resolve this.

If there are any further issues, please reopen this ticket.
