### ISSUE TITLE
Medellin Cartel - Level 1 Rewards

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/saesrpg-web#185]
Hi there,

I would like to request the rewards claim for the gang " Medellin Cartel" for reaching Level 1.

Group owner: WenDo (https://saesrpg.uk/user/wendo)
Group name: Medellin Cartel
Logo: https://i.imgur.com/5S8BkBH.png
Public forum name: Medellin Cartel
Group color: #9b6c62
Subcategories:

1. "Application Center" = Which will be intended for new applicants to post their applications and find info about our membership.
-- "Archive" = If it's a possibility to have another sub inside the "Application Center" where old applications / info get archived.

And we like to move our main topic + media into the public forum (https://saesrpg.uk/topic/14142/medellin-cartel-level-1)
(https://saesrpg.uk/topic/14143/medellin-cartel-media-archive)

Forum Moderators who fully moderate the forum and subcategories.

WenDo - https://saesrpg.uk/user/wendo
MarksMan - https://saesrpg.uk/user/marksman

Thanks in advance!

WenDo, Leader of Medellin

**Comment by SAESKain** [comment]
Yeah you're not getting that many subcategories, just use the public one for that.

Also logo doesnt work, probably too big
