### ISSUE TITLE
Forum moderation rights request

### ISSUE THREAD

**Issue by DemienD** [saesrpg/saesrpg-web#19]
Hello,

I am requesting forum mod rights for the following sections:
`Desert Eagles > Archive` [Link](https://saesrpg.uk/category/214/archive)
`Desert Eagles > Desert Eagles - New Recruit Info` [Link](https://saesrpg.uk/category/215/desert-eagles-new-recruit-info)
`Desert Eagles > Airborne Unit` [Link](https://saesrpg.uk/category/261/airborne-unit)
`Desert Eagles > Assault Unit` [Link](https://saesrpg.uk/category/260/assault-unit)
`Desert Eagles > Naval Unit` [Link](https://saesrpg.uk/category/262/naval-unit)

For the user [DyamDouglas](https://saesrpg.uk/user/dyamdouglas)
Request is permitted by SAES>Patrol

Thanks in advance,
Regards,

Dyam Douglas

**Comment by SAESKain** [comment]
"Request is permitted by SAES>Patrol"

When are you people gonna learn to start posting evidence.

**Comment by DemienD** [comment]
![image](https://user-images.githubusercontent.com/15146566/52556093-d116af00-2deb-11e9-8a43-cddd3cf12bd9.png)
Does this count?

**Comment by DemienD** [comment]
In addition I would like to request access to DEHQ private subforum.

https://photos.app.goo.gl/wuy2daHhZnxPfPdZ9

**Comment by saesrpg** [comment]
Done
