### ISSUE TITLE
Hell Hounds Motorcycle Club Forums

### ISSUE THREAD

**Issue by brondy** [saesrpg/saesrpg-web#193]
Hi,

We would like to request a public subforum within the 'groups' section with a few subcategories which can be found below.

Group owner: Brondy (https://saesrpg.uk/user/brondy)
Group name: Hell Hounds Motorcycle Club
Public forum name: Hell Hounds MC
Group color: #620677

Subcategories:

- "Recruitment and Membership" = "For applications and membership informations"

- "Applications Archive" = If it's a possiblity to have another sub inside the "Recruitment and Membership"

- "Members Area" = "A section that only members of our forum group can see"

And we like to move our main topic into the public forum (
hhttps://saesrpg.uk/topic/5358/hell-hounds-motorcycle-club 
https://saesrpg.uk/topic/5364/hell-hounds-motorcycle-club-media-archive )

Forum Moderators who fully moderate the forum and subcategories.

Brondy (https://saesrpg.uk/user/brondy)
Sneijder (https://saesrpg.uk/user/sneijder)
Griffin (https://saesrpg.uk/user/griffin)
Thanks in advance!

**Comment by SAESKain** [comment]
Pending group manager approval

**Comment by IEDaryl** [comment]
This wasn't approved by group management and we were not contacted in advance of this request. 60 media posts in nearly 18 months is certainly not deserving of a forum reward.
