### ISSUE TITLE
FIX FORUM SPOILERS

### ISSUE THREAD

**Issue by Ramos116** [saesrpg/saesrpg-web#199]
When i try to add pics in spoiler, in preview everyhting looks fine, once i submit topic, same pic repeats  in each spoiler. fix that

https://imgur.com/a/Hqi2Gk1

**Comment by saesrpg** [comment]
Report it to the author of the spoiler plugin please: https://github.com/NicolasSiver/nodebb-plugin-ns-spoiler

**Comment by Scorpyooooo** [comment]
Quoted from https://github.com/NicolasSiver/nodebb-plugin-ns-spoiler/issues/23

> Change it to have extra lines between the code symbols:
> 
> ```
> :::
> 
> something
> 
> :::
> ```
