### ISSUE TITLE
All-italic home page

### ISSUE THREAD

**Issue by itsmatheus** [saesrpg/saesrpg-web#20]
Everything in the home page below "**Note:** *Those who don't feel comfortable with others having fun please refra...*" is in italic, probably since the markdown from the news article page didn't end properly.

Maybe do not use markdown for article descriptions as an easy fix?
[Screenshot](https://i.imgur.com/LsUvSX4.png)

**Comment by saesrpg** [comment]
It's an issue with an external plugin, it will be reported with them.
