### ISSUE TITLE
SAFP New Moderation Rights

### ISSUE THREAD

**Issue by wizax49** [saesrpg/saesrpg-web#203]
Dear SAES Web Managers,

As I am the new SAFP Leader I'd like to request moderation rights for the following users, Please.

Wizax (( https://saesrpg.uk/user/wizax ))
Laminee (( https://saesrpg.uk/user/laminee ))

Thanks in advance;
Commissioner Wizax;
San Andreas Federal Police.

**Comment by SAES-Magnus** [comment]
Rejected since Halo is the leader again.
