### ISSUE TITLE
Cuban Cars forums mod

### ISSUE THREAD

**Issue by MasterYoko** [saesrpg/saesrpg-web#207]
Hi there,

I'd like to be provided with mod rights on Cuban Cars forums.

https://saesrpg.uk/category/177/cuban-cars 
https://saesrpg.uk/category/178/cuban-cars-members

Profile: https://saesrpg.uk/user/yoko_kurama

Thank you in advance,
Regards.

**Comment by SAES-Magnus** [comment]
Sorted
