### ISSUE TITLE
Fight Club Forum Group & Private Forums Request

### ISSUE THREAD

**Issue by AdemBygt** [saesrpg/saesrpg-web#208]
Hi,

We would like to request a public subforum within the 'groups' section with a few subcategories which can be found below.

Group owner: AdemBygt  (https://saesrpg.uk/user/adembygt)
Group name: Fight Club
Public forum name: Fight Club
Group color: #966900

Subcategories:

"Recruitment and Membership" = "For applications and membership informations"

"Applications Archive" = If it's a possiblity to have another sub inside the "Recruitment and Membership"

"Members Area" = "A section that only members of our forum group can see"

And we like to move our main topic into the public forum 
(
https://saesrpg.uk/topic/13741/fight-club-offical-topic
hhttps://saesrpg.uk/topic/13742/fight-club-offical-media-archive 
)

Forum Moderators who fully moderate the forum and subcategories.

Adem (https://saesrpg.uk/user/adembygt)
Zaza (https://saesrpg.uk/user/zaza)
Paraodox  (https://saesrpg.uk/user/paradox)
Thanks in advance!

**Comment by saesrpg** [comment]
Your request has not been approved by group management.

Please speak to group managment if you wish to discuss this further and feel free to recreate this request once they have approved it.
