### ISSUE TITLE
Adding members to per-user forum section

### ISSUE THREAD

**Issue by tutgreco** [saesrpg/saesrpg-web#21]
Oi

I would like the following users added to the [SAPA instructor forum](https://saesrpg.uk/category/188/instructors-section)

https://saesrpg.uk/user/kristiina
https://saesrpg.uk/user/dyamdouglas
https://saesrpg.uk/user/w1seoldman
https://saesrpg.uk/user/itsme
https://saesrpg.uk/user/alperreis
https://saesrpg.uk/user/laza
https://saesrpg.uk/user/riley
https://saesrpg.uk/user/flusha
https://saesrpg.uk/user/firefox
https://saesrpg.uk/user/qweezy
https://saesrpg.uk/user/bas260
https://saesrpg.uk/user/herrjorss
https://saesrpg.uk/user/istar
https://saesrpg.uk/user/suki

note: some may already be able to view the forum, i'm not able to check though

**Comment by SAESKain** [comment]
Group given instead cus not a chance was i adding all of those individually
