### ISSUE TITLE
Forum group with a public forums for The Classic Klan

### ISSUE THREAD

**Issue by gxnzo12** [saesrpg/saesrpg-web#210]
Hello there.

I would like to request a public subforum within the 'groups' section with a few subcategories which can be found below.

Group owner: Poxiran(https://saesrpg.uk/user/poxiran)
Group name: The Classic Klan
Public forum name: The Classic Klan
Group color: #BF737B

Subcategories:

"Recruitment" = "For applications"

"Applications Archive" = If it's a possiblity to have another sub inside the "Recruitment"

"Members Area" = "A section that only members of our forum group can see"

We like to move our main topic into the public forum
( https://saesrpg.uk/topic/16080/the-classic-klan )
( https://saesrpg.uk/topic/16079/the-classic-klan-media-archive )

Forum Moderators who fully moderate the forum, public forum and subcategories.

Poxiran(https://saesrpg.uk/user/poxiran)
Gonza(https://saesrpg.uk/user/gonza)
PerrooLocoo(https://saesrpg.uk/user/perroolocoo)
Douglass(https://saesrpg.uk/user/douglass)

Thanks in advance.

**Comment by saesrpg** [comment]
You need to speak to group managment to get this approved before requesting it.

Feel free to reopen this issue once you have it.
