### ISSUE TITLE
[Forums] People can't change avatars [Bug]

### ISSUE THREAD

**Issue by XgangsterX** [saesrpg/saesrpg-web#212]
Error

Something went wrong installing the "sharp" module The module '/var/saesrpg/node_modules/sharp/build/Release/sharp.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 57. This version of Node.js requires NODE_MODULE_VERSION 72. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`). - Ensure the version of Node.js used at install time matches that used at runtime - Consult the installation documentation at https://sharp.pixelplumbing.com/install - Search for this error at https://github.com/lovell/sharp/issues****

**Comment by saesrpg** [comment]
This is fixed.
