### ISSUE TITLE
Requesting mod in lounge section

### ISSUE THREAD

**Issue by bangas69** [saesrpg/saesrpg-web#215]
Recently i got promoted to Lounge executive and i´d like to access the mod to lounge foruns.Note that assasin gave me permition to have tmod rights.
Screens: https://imgur.com/a/COXKP2K
lounge foruns: https://saesrpg.uk/category/137/lounge-vc
my profile:https://saesrpg.uk/user/bangas

**Comment by LoungeVC** [comment]
Confirmed by Lounge VC.
Please, also do add the following accounts to the forums' access:
https://saesrpg.uk/user/blu%C3%A9
https://saesrpg.uk/user/xavier
https://saesrpg.uk/user/oleg

**Comment by BlueSAES** [comment]
BUMP
