### ISSUE TITLE
Hell Soldiers private forum

### ISSUE THREAD

**Issue by kockata666** [saesrpg/saesrpg-web#218]
Hey, I would like to request our forum
If its possible to get our main thread and media archive under our forum
Mods on the forum
Rzz0: https://saesrpg.uk/user/rzz0
Lamza: https://saesrpg.uk/user/lamza
Candy: https://saesrpg.uk/user/candy
Nobody: https://saesrpg.uk/user/nobodyknows
Kockata: https://saesrpg.uk/user/kockata
Color: 55218c
Logo: https://imgur.com/a/zw3relf

**Comment by Markus139** [comment]
bump
