### ISSUE TITLE
Mod rights for SAPA forum

### ISSUE THREAD

**Issue by bas260** [saesrpg/saesrpg-web#22]
I'm requesting to be added to forum moderator in the following sections.
You can confirm with SAES>Royalty.

https://saesrpg.uk/category/41/sapa
https://saesrpg.uk/category/184/application-section
https://saesrpg.uk/category/185/application-archive
https://saesrpg.uk/category/186/education-section
https://saesrpg.uk/category/187/education-archive 
https://saesrpg.uk/category/188/instructors-section

**Comment by tutgreco** [comment]
we will not grant moderation to you yet, as explained in discord
