### ISSUE TITLE
The Motor Heads forum edit

### ISSUE THREAD

**Issue by Scorpyooooo** [saesrpg/saesrpg-web#23]
Hello
I'd like to request viewing right on [this forum](https://saesrpg.uk/category/175/hq-area) for those 2 users : [Lincoln](https://saesrpg.uk/user/lincoln) and [Brooks](https://saesrpg.uk/user/brooks) and remove Xpooks

Also add a public sub forum [here](https://saesrpg.uk/category/173/the-motor-heads-tmh) with the name “TMH Vehicle Auction”, and a sub forum with the name"Vehicle Auction Archive" inside of it, accessible only for the people with permission to view the [hq sub forum](https://saesrpg.uk/category/175/hq-area)
Add same moderators as the main TMH section to this new sub forum

Thanks

**Comment by saesrpg** [comment]
Done
