### ISSUE TITLE
Lounge VC Subforum

### ISSUE THREAD

**Issue by AkyZ-collab** [saesrpg/saesrpg-web#231]
Hello,

Lounge VC would like to request two subforum's. One called RaceWars and the other one being called Gang Wars.

Mod rights for the Gang Wars subforum:

Gang Wars: 

https://saesrpg.uk/user/akyz
https://saesrpg.uk/user/assassin
https://saesrpg.uk/user/bangas

RaceWars:

https://saesrpg.uk/user/jay
https://saesrpg.uk/user/akyz
https://saesrpg.uk/user/assassin
https://saesrpg.uk/user/bangas

**Comment by SAES-Jay** [comment]
GM has approved, good to go.
