### ISSUE TITLE
Different profile pictures on mobile and pc

### ISSUE THREAD

**Issue by mrgamer101** [saesrpg/saesrpg-web#238]
I recently updated my profile picture on the forums on my PC but the picture did not update on the mobile version of the forums. This is what the mobile version looks like for me (with the old profile pic):
https://i.imgur.com/vmgR5ie.jpg

And this is the PC version (with the updated profile picture):
https://i.imgur.com/dmXHodP.png

**Comment by tutgreco** [comment]
@mrgamer101 did you try clicking `CTRL F5` after saving the changes?

**Comment by mrgamer101** [comment]
@tutgreco nope, just followed the instructions

**Comment by mrgamer101** [comment]
Just to clarify, the inconsistency was present for a couple of weeks after I updated my profile up until I updated it again today.

**Comment by SAES-Magnus** [comment]
Did you try to logout and in again on your phone?

**Comment by mrdavidfry** [comment]
I did not try that.

**Comment by mrgamer101** [comment]
I did not try that.

**Comment by Liyones** [comment]
Hello @mrgamer101 
it happened to me when u upload a pic in your profile in pc u have to click ctrl + f5 it will be changed in pc but if u open phone u will still get the old one 
what to do then ? just delet the history of phone everything cookies/accounts/... everything in history then reload saes page and login again , Enjoy !
