### ISSUE TITLE
Emoji images not being served with HTTPS

### ISSUE THREAD

**Issue by mrgamer101** [saesrpg/saesrpg-web#239]
Some emoji images are being loaded without using HTTPS. These emojis are used when players post comments (e.g by writing :honk:), and the images are preventing the connection from being displayed as "fully secure" in the browser (chrome in my case). This may reduce the trust that users have in the site even though everything else is served with HTTPS. Attackers may also be able to modify these images. This bug only happens when you view a page/topic that has used emojis.

Here's what's displayed in the console:
https://i.imgur.com/X1xabxY.png

**Comment by saesrpg** [comment]
This is now fixed.
