### ISSUE TITLE
Forums addition

### ISSUE THREAD

**Issue by lekoxcom** [saesrpg/saesrpg-web#240]
Hello,I am working on the progress of the CDC. I would like to have 100% direct access to all the forums of the CDC to mannage that and make it better, ill be happy if you guys can Help me with that! thank you!

**Comment by SAES-Magnus** [comment]
And you are who exactly? We can't add you to anything if you don't provide us with your forum name. And if you aren't a HQ in CDC then this has to be requested by someone who are.

**Comment by lekoxcom** [comment]
Hello i was BaNdiToBill, i founded CDC, i was some years inactive from the
game, now i back and got the leadership of cdc to try save these gang when
julio as inactive,
My game login is lekoxcom
My forum user @BaNdiToBill
