### ISSUE TITLE
IAC Forum

### ISSUE THREAD

**Issue by MTAParadox** [saesrpg/saesrpg-web#244]
Hello lads;
People who apply at 'Recruitment Section' cant edit their posts and this causing some problems, applications should be able to edit their posts in mentioned section
IAC Forum Moderators cant delete topic/shitposts at IAC forums so we want to have this ability
IAC Archive should be  visible  for Moderators only
Also one last thing people sending a picture at spoiler and its not visible here is an example [Here](https://saesrpg.uk/topic/17146/beast-s-iac-application-accepted). Check the spoiler below application.

Ty for your helps...

**Comment by SAES-Magnus** [comment]
Everything is sorted.

When it comes to having pictures in spoilers, that seems to be a bug with the forum not just your section.
