### ISSUE TITLE
Requesting a protected subforum for Desert Eagles Special Forces

### ISSUE THREAD

**Issue by DemienD** [saesrpg/saesrpg-web#25]
Hello SAESHQ,

I'd like to request a subforum `Special Forces Intelligence Unit` [here](https://saesrpg.uk/category/74/desert-eagles).
We would like to have it protected and accessible only to specific members. So, to accommodate for that, I'm requesting either the following members added:

- https://saesrpg.uk/user/dyamdouglas
- https://saesrpg.uk/user/patrol
- https://saesrpg.uk/user/bunny
- https://saesrpg.uk/user/tayber
- https://saesrpg.uk/user/darius
- https://saesrpg.uk/user/strong
- https://saesrpg.uk/user/xtrade
- https://saesrpg.uk/user/crash
- https://saesrpg.uk/user/ig8820
- https://saesrpg.uk/user/absent
- https://saesrpg.uk/user/hassoni
- https://saesrpg.uk/user/dufabo

I can imagine this isn't the most useful way of things, so perhaps you could make a forum group instead.

Proof of approval by Patrol:
![image](https://user-images.githubusercontent.com/15146566/53732564-a36ad600-3e7e-11e9-9c67-0cbcfcd86d34.png)

Thanks in advance.

**Comment by Hahnfruh** [comment]
It is done.
