### ISSUE TITLE
Unread posts message is bugged

### ISSUE THREAD

**Issue by tut98** [saesrpg/saesrpg-web#254]
This seems to have occured today or yesterday.
### Issue: 
![image](https://user-images.githubusercontent.com/46188218/87590824-b7b41980-c6e7-11ea-9646-5af3bdcb9dbe.png)

___

### Intended:
![image](https://user-images.githubusercontent.com/46188218/87591208-46c13180-c6e8-11ea-85e8-51e35497f737.png)

**Comment by tutgreco** [comment]
It looks like it's back to normal now, after the update this evening
