### ISSUE TITLE
SAES forum bug 

### ISSUE THREAD

**Issue by Liyones** [saesrpg/saesrpg-web#257]
Hello, this bug started since a week so when i was reading a topic it load/open other topic auto from Inactive requests forum or donation topics forum ,
Example:
https://imgur.com/vz000u7
it changed to this page:
https://imgur.com/AWtyihp

it didn't happen first time , it happened to me many times this week maybe 20
NOTE: it open only new topics for atleast 1 day

**Comment by Velona77** [comment]
This happens whenever someone locks & moves a topic (for my example that was always SAHA Inactive requests)
I had multiple tabs open, all of them turned to be the topic I archived in SAHA sub-forum.
