### ISSUE TITLE
FBI Forum Moderation request

### ISSUE THREAD

**Issue by Qweezy331** [saesrpg/saesrpg-web#26]
Please give this user the ability to moderate the FBI main and HQ forums.
Link to user: https://saesrpg.uk/user/johnturner
Link to FBI forums: https://saesrpg.uk/category/78/federal-bureau-of-investigation
Link to FBI HQ forums: https://saesrpg.uk/category/176/executive-bureau
Thanks in advance

**Comment by saesrpg** [comment]
Done
