### ISSUE TITLE
ALT subforum mod

### ISSUE THREAD

**Issue by Kowalski1245** [saesrpg/saesrpg-web#266]
Hello,

I would like to request full mod rights for the ALT sub forums. Here is the account:  https://saesrpg.uk/user/kowalski

**Comment by saesrpg** [comment]
@Kowalski1245 can you please get a member of ALT HQ to confirm this here please.

**Comment by SScorpyo** [comment]
Confirmed

**Comment by saesrpg** [comment]
This is now done.
