### ISSUE TITLE
Cunning Stunts subforum Mod

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/saesrpg-web#267]
Hey there, 

I would like to request all moderator rights for my forum account to the Subforum group of Cunning Stunts

Accname: https://saesrpg.uk/user/wendo
Subgroup: https://saesrpg.uk/category/163/cunning-stunts

Thanks in advance!

**Comment by saesrpg** [comment]
@WenDo21 can you get a member of CS to confim this here please.

**Comment by WenDo21** [comment]
https://i.imgur.com/YzNRTtF.png

@saesrpg +
