### ISSUE TITLE
Niggaz wit Attitudes forum request

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/saesrpg-web#268]
Hi there
I would like to request our forum rewards

Our tag: Niggaz wit Attitudes
Our color: 1E0B21 

 **Sub Forum**

Name: Niggaz wit Attitudes
 
These two will be moved as well: 

Our main topic: (https://saesrpg.uk/topic/20245/niggaz-wit-attitudes?page=1)

Our media archive: (https://saesrpg.uk/topic/20246/niggaz-wit-attitudes-media-archive?page=1)

Moderators:
https://saesrpg.uk/user/laggiaze
https://saesrpg.uk/user/dizzy
https://saesrpg.uk/user/brondy
https://saesrpg.uk/user/durby

**Comment by saesrpg** [comment]
This is now done @laggiaze
