### ISSUE TITLE
Outbreak Organization Forum Request

### ISSUE THREAD

**Issue by MasterYoko** [saesrpg/saesrpg-web#27]
Hello there guys I'll like to request a forum for our organization, we've been around for at least 4 month after being inactive for a couple of years. We had our forums/base before, however lost it due to our inactivity back in 2015. We're back now as I stated before full of activity. You guys can check our...

- Official topic: https://saesrpg.uk/topic/4129/outbreak-organization?page=1
- Media Archive: https://saesrpg.uk/topic/4130/outbreak-organization-media-archive
-https://discord.gg/UsfctGy (Where you will be able to notice see how organized is everything in regarding the criminal organization).

We've done already over 65 events, and over 80 Jailbreaks, Organized jailbreaks though (that's our main role) and Roleplays aswell, Quality Roleplays.

If the forums are approved I'd like to request the ''Outbreak Organization'' Public Section, ''Outbreak Members Forums" section, and one for our HQs ''Outbreak HQ Forums" section.

The moderation rights are for both forums (Outbreak Members Forumsand Outbreak HQ Forums) and the hq's moderation will be for the next users:
User 1: https://saesrpg.uk/user/yoko_kurama
User 2: https://saesrpg.uk/user/coldplay
User 3: https://saesrpg.uk/user/julio
User 4: https://saesrpg.uk/user/terry
User 5: https://saesrpg.uk/user/velona

Thanks in advance.

**Comment by saesrpg** [comment]
Done

**Comment by saesrpg** [comment]
I've also setup your forum group
