### ISSUE TITLE
Emoji pack issue

### ISSUE THREAD

**Issue by tut98** [saesrpg/saesrpg-web#275]
What I get in the emoji window: 
![image](https://user-images.githubusercontent.com/46188218/93329412-74784300-f81d-11ea-9885-fcebd39e4638.png)

What I get in the reply window: 
![image](https://user-images.githubusercontent.com/46188218/93329437-7d691480-f81d-11ea-8a08-e4a6d0030414.png)

Is this an issue on my end? I'm on Google Chrome (PC)

**Comment by saesrpg** [comment]
Fixed.
