### ISSUE TITLE
Los INKAS Forum Updates

### ISSUE THREAD

**Issue by Chafloque** [saesrpg/saesrpg-web#278]
_Hello Dear Forum Managers.
I would like to request some updates related to our Media Archive and Forums._

- _Give full moderator rights (move, pin, edit, etc..) in the_ **INKAS FORUMS** _to_ [Kakaroto ](https://saesrpg.uk/user/marcofercam) , [Dioni ](https://saesrpg.uk/user/dioni) , [Kodigo ](https://saesrpg.uk/user/kodigo) and [Alessio ](https://saesrpg.uk/user/alessio)

- In some way, **Delete or Disappear**, posts made in the wrong way in Los INKAS Forums.(more specifically, those highlighted in the photo)
![Sepis](https://user-images.githubusercontent.com/64719074/94596294-8f9d7680-0251-11eb-94ca-0c430dd5d105.png)

**Comment by saesrpg** [comment]
This is now done @Chafloque , however, we have disabled the permission to "purge" topics in case a HQ member of gangs/groups start wiping maliciously deleting data.

These topics are only visible to moderators.
