### ISSUE TITLE
GXT - Forum Moderation Rights

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/saesrpg-web#279]
Hello there,

I would like to request full mod rights for MarksMan and myself as we are new HQs of GXT.

Subforum: https://saesrpg.uk/category/394/global-express-trucking-company
MarksMan Profile: https://saesrpg.uk/user/marksman
My Profile: https://saesrpg.uk/user/wendo

Confirmation picture: https://i.imgur.com/tTg4uro.png

Thanks in advance!

**Comment by saesrpg** [comment]
This is now done @WenDo21
