### ISSUE TITLE
Requesting TST HQ Forum/TST Forum Moderation Request

### ISSUE THREAD

**Issue by N-FUN** [saesrpg/saesrpg-web#28]
We would like to request our private HQ forum within the TST forum. If possible name it ''Commander Office''
Accusable for the following people.
Link to users:
https://saesrpg.uk/user/n-fun 
https://saesrpg.uk/user/bidrift 
https://saesrpg.uk/user/bangas 
https://saesrpg.uk/user/danny2106 
https://saesrpg.uk/user/rocker 
https://saesrpg.uk/user/john
https://saesrpg.uk/user/gravity 

Moderate rights within the HQ forum.
Link to users:
https://saesrpg.uk/user/john 
https://saesrpg.uk/user/rocker 
https://saesrpg.uk/user/n-fun
https://saesrpg.uk/user/gravity  

We also would like to request moderate rights within our normal forum  for the following people:
https://saesrpg.uk/user/n-fun 
https://saesrpg.uk/user/bidrift 
https://saesrpg.uk/user/bangas 
https://saesrpg.uk/user/danny2106 
https://saesrpg.uk/user/rocker 
https://saesrpg.uk/user/john
https://saesrpg.uk/user/gravity 
Link to TST forum: https://saesrpg.uk/category/120/the-strike-team 

Sincerely,

The Strike Team HQ
N.FUN

**Comment by saesrpg** [comment]
Done
