### ISSUE TITLE
RadioSA - Forum Moderation Rights

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/saesrpg-web#280]
Hello there,

Garcia and me got promoted in RadioSA recently to HQ position and I would like to request full moderation rights on forums for both of us

Accounts
Garcia: https://saesrpg.uk/user/garcia
WenDo: https://saesrpg.uk/user/wendo

Subforum: https://saesrpg.uk/category/244/radio-sa

Thanks in advance!

**Comment by Garcia125** [comment]
@SAES-Magnus

**Comment by saesrpg** [comment]
This is now done @WenDo21
