### ISSUE TITLE
Los Lunas Forum Request

### ISSUE THREAD

**Issue by Matto582** [saesrpg/saesrpg-web#281]
Hi there
I would like to request our forum rewards

Our tag: Lunas|>Name
Our color: 855521

Sub Forum

Name: ✪Los Lunas✪

These two will be moved as well:

Our main topic: (https://saesrpg.uk/topic/20374/los-lunas-official-topic?page=1)

Our media archive: (https://saesrpg.uk/topic/20376/los-lunas-media-archive?page=1)

Moderators:
https://saesrpg.uk/user/matt0
https://saesrpg.uk/user/vex
https://saesrpg.uk/user/twister
https://saesrpg.uk/user/mateus

**Comment by saesrpg** [comment]
This is now done @Matto582
