### ISSUE TITLE
X Forums change

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-web#294]
I'd like to remove whoever isn't in the following list from moderating our forums section: https://saesrpg.uk/category/431/generation-x

1- Mrwan (https://saesrpg.uk/user/mrwan)
2- Rover (https://saesrpg.uk/user/rover)
3- Jizzy (https://saesrpg.uk/user/jizzy)
4- M7md (https://saesrpg.uk/user/m7mdgr7)
5- Bor (https://saesrpg.uk/user/bor)

Thanks In advance

**Comment by saesrpg** [comment]
This is now done
