### ISSUE TITLE
HRMC - Level 1 (Private Forum, Private Role)

### ISSUE THREAD

**Issue by Franklin880** [saesrpg/saesrpg-web#297]
A private forum group/role named "Hell Raisers MC" and a private forum attached to it

Admins of the group should be:
https://saesrpg.uk/user/franklin
https://saesrpg.uk/user/woytex
https://saesrpg.uk/user/tomaz96
https://saesrpg.uk/user/mrthomas
https://saesrpg.uk/user/thamond

We would also like our main topic and media archive to be moved from where it is into the subcategories section in gangs next to our private forum.
https://saesrpg.uk/topic/23480/hell-raisers-mc-main-topic?page=1
https://saesrpg.uk/topic/5087/hell-raisers-mc-media-archive?page=1

**Comment by jonathdb93** [comment]
- Group created
- Subforum and private forum created
- Topics moved

Currently there is still an issue concerning group badges, we're looking into this further
