### ISSUE TITLE
GSF Privet forum 

### ISSUE THREAD

**Issue by voli1** [saesrpg/saesrpg-web#298]
i'd like to get a private forum with #013621 color "dark green" Named Grove Street Family  also if possible to have moderator voli , nicky  & derrick (Admins for all sections both public & private )
https://saesrpg.uk/user/voli
https://saesrpg.uk/user/nicky
https://saesrpg.uk/user/derrick
with HQ's voli , nicky & derrick 
and  last but not least i want to move our media & main topic to the subcategories section in gangs next to our privet forum 
https://saesrpg.uk/topic/23483/grove-street-family/4?page=1
https://saesrpg.uk/topic/23481/grove-street-family-media-archive

**Comment by jonathdb93** [comment]
* Forum group created
* Subforum created
* Private forum created
* Posts moved
