### ISSUE TITLE
Multiple spoilers (n + 1) looses reference to spoiler.unloadImages function.

### ISSUE THREAD

**Issue by ghost** [saesrpg/saesrpg-web#299]
When a user adds a 2nd spoiler, the spoiler.js script can't properly reference the spoiler to unload images from:

![image](https://user-images.githubusercontent.com/15146566/107559714-bb0b7700-6bdc-11eb-9e83-8a8cfc9d38d5.png)

Example at:
https://saesrpg.uk/post/277113
^ Has since been edited. When spoilers contain the exact same content it does work

**Comment by saesrpg** [comment]
We use this plugin for spoilers, if anyone wish to take a look at forking or doing a PR

https://github.com/NicolasSiver/nodebb-plugin-ns-spoiler

**Comment by saesrpg** [comment]
This was fixed when we changed our spoiler plugin.
