### ISSUE TITLE
Mod rights for SAPA forums

### ISSUE THREAD

**Issue by tutgreco** [saesrpg/saesrpg-web#3]
I would like additional forum moderators for the following SAPA forum sections:

https://saesrpg.uk/category/41/sapa - iTsMe, Royalty, Zeking
https://saesrpg.uk/category/184/application-section - iTsMe, Royalty, Zeking
https://saesrpg.uk/category/185/application-archive - iTsMe, Royalty, Zeking
https://saesrpg.uk/category/186/education-section - iTsMe, Royalty, Zeking
https://saesrpg.uk/category/187/education-archive - iTsMe, Royalty, Zeking
https://saesrpg.uk/category/188/instructors-section - iTsMe, Royalty, Zeking
https://saesrpg.uk/category/189/headquarters-section - Royalty, Zeking

forum profiles: [ZekinG](https://saesrpg.uk/user/zeking), [Royalty](https://saesrpg.uk/user/royalty), [iTsMe](https://saesrpg.uk/user/itsme)

thank you in advance :+1:

**Comment by saesrpg** [comment]
This is now done
