### ISSUE TITLE
Military Academy Forum Changes 

### ISSUE THREAD

**Issue by CrashSystem** [saesrpg/saesrpg-web#30]
I would like to organize this forum sections to fall under the Private one

Also would like to get a new section inside the Private one named Cadets Profile 

Private>Archive,Cadets Profile and the  HQ 

Modded rights to :

https://saesrpg.uk/user/sou
https://saesrpg.uk/user/marko
https://saesrpg.uk/user/crash

And remove the following people from the HQ forum

https://saesrpg.uk/user/qweezy
https://saesrpg.uk/user/john
https://saesrpg.uk/user/breezy
https://saesrpg.uk/user/tut-greco

**Comment by saesrpg** [comment]
Done
