### ISSUE TITLE
cripz moderator permission

### ISSUE THREAD

**Issue by protonyt** [saesrpg/saesrpg-web#301]
**I'd like to remove everyone's moderation rights from cripz's sub-forum and add these profiles:**

* https://saesrpg.uk/user/zaza
* https://saesrpg.uk/user/adembygt
* https://saesrpg.uk/user/ares
* https://saesrpg.uk/user/protonyt
* https://saesrpg.uk/user/stalin
* https://saesrpg.uk/user/alperens
* https://saesrpg.uk/user/flora
* https://saesrpg.uk/user/exalted

***cripz sub-forums:***
* https://saesrpg.uk/category/149/cripz

**Comment by jonathdb93** [comment]
Sorted, also took care of the Cripz HQ/Private/Archive subcategories
