### ISSUE TITLE
HS 

### ISSUE THREAD

**Issue by kockata666** [saesrpg/saesrpg-web#303]
could you give those guys mod rights over HS forum

jccx https://saesrpg.uk/user/jccx
petrow https://saesrpg.uk/user/petrow
homeless https://saesrpg.uk/user/homeless
mr.khaled https://saesrpg.uk/user/mr-khaled
henry https://saesrpg.uk/user/henry
lorch https://saesrpg.uk/user/lorch

**Comment by jonathdb93** [comment]
All users have been granted mod rights
