### ISSUE TITLE
New SAFP Moderators on our forums

### ISSUE THREAD

**Issue by halomiro** [saesrpg/saesrpg-web#305]
Hello there.

We want these moderators:

https://saesrpg.uk/user/halo

https://saesrpg.uk/user/lapd_spanish_ven

https://saesrpg.uk/user/zoro

https://saesrpg.uk/user/xhamster

https://saesrpg.uk/user/kristiina

https://saesrpg.uk/user/landshark

https://saesrpg.uk/user/tefa

Regards

**Comment by jonathdb93** [comment]
Solved
