### ISSUE TITLE
MMC Subforum 

### ISSUE THREAD

**Issue by Killerask** [saesrpg/saesrpg-web#306]
I would like to request subforum for MMC and move the media and topic

LINK MEDIA https://saesrpg.uk/topic/24380/mongols-mc-media-archive?page=1

LINK TOPIC https://saesrpg.uk/topic/24378/mongols-mc?page=1

Moderators : 
https://saesrpg.uk/user/killerask
https://saesrpg.uk/user/dawis67

**Comment by jonathdb93** [comment]
Sorted!
