### ISSUE TITLE
BloodZ  Privet forum 

### ISSUE THREAD

**Issue by anxhelo00** [saesrpg/saesrpg-web#307]
I would like to get a private forum with color # C20000 named BloodZ, and if possible moderator BlaZe, CaPu, Chezzy (To control our private and public sections)
**Moderators** 
https://saesrpg.uk/user/blaze
https://saesrpg.uk/user/thedarkcapu
https://saesrpg.uk/user/chezzy

**Media Link** : https://saesrpg.uk/topic/25638/bloodz-media-archive?page=1
**Topic Link :** https://saesrpg.uk/topic/25633/bloodz?_=1617580839893

**Comment by jonathdb93** [comment]
Sorted
