### ISSUE TITLE
Royal Flush lvl1 rewards - Private forum

### ISSUE THREAD

**Issue by KingNevs** [saesrpg/saesrpg-web#308]
A private forum group/role named "Royal Flush" and a private forum attached to it,

Admins of the group should be:
https://saesrpg.uk/user/nevs
https://saesrpg.uk/user/thamond
https://saesrpg.uk/user/villain

We would also like our main topic and media archive to be moved from where it is into the subcategories section in gangs next to our private forum.
Main topic: https://saesrpg.uk/topic/25248/royal-flush?page=1
Media archive: https://saesrpg.uk/topic/25249/royal-flush-media-archive

**Comment by jonathdb93** [comment]
Sorted
