### ISSUE TITLE
BRINKS Forum Request.

### ISSUE THREAD

**Issue by ZoRo12425** [saesrpg/saesrpg-web#315]
**Hello there,**
Here I am requesting A forum group named "**BRINKS**" and a private forum attached to it.
**Color Code:** #8F8161
**HQ Team:**
https://saesrpg.uk/user/zoro
https://saesrpg.uk/user/afufu
https://saesrpg.uk/user/lapd_spanish_ven
https://saesrpg.uk/user/rocoso?_=1623000722420
https://saesrpg.uk/user/skomorje
https://saesrpg.uk/user/aveyro?_=1623000722423

I would Like you to move our topic and media to our forums.
**Topic:** https://saesrpg.uk/topic/25866/brinks-main-topic
**Media:** https://saesrpg.uk/topic/25865/brinks-media-archive

**Comment by ALIJR007** [comment]
The above has been approved by GMs. The HQ structure is the following;

Spanish - L
Afufu - vL

Rocoso - HQ
Zoro - HQ

Aveyro - sHQ
Skomorje - sHQ

**Comment by saesrpg** [comment]
This is now done @x-Afufu @ZoRo12425
