### ISSUE TITLE
Defence Intelligence Agency - Level 1 Rewards

### ISSUE THREAD

**Issue by JukyPlatinium** [saesrpg/saesrpg-web#316]
Private Forum Groupe named"Defence Intelligence Agency" and a private forum attached to it
Color Code= # 54EAFE
Moderators(HQ's):
https://saesrpg.uk/user/jukyplatinium
https://saesrpg.uk/user/remp
https://saesrpg.uk/user/razak
https://saesrpg.uk/user/Frizi

Also we would like to move our media archive and topic to our private forums

Main Topic: https://saesrpg.uk/topic/26402/defence-intelligence-agency-official-topic?_=1623017303641
Media Archive: https://saesrpg.uk/topic/26404/defence-intellingence-agency-media-archive?page=1

**Comment by jonathdb93** [comment]
Request has been sorted and verified
