### ISSUE TITLE
Forum topic thumbnails doesn't work anymore

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/saesrpg-web#319]
Forum topic thumbnails doesn't work anymore
The last one was closed but still wont working. 
https://github.com/saesrpg/saesrpg-web/issues/311#issuecomment-863315255

**Comment by saesrpg** [comment]
This feature was left on by accident and shouldn't have been used as it clogs the server with unnecessary files.

This has now been turned off.
