### ISSUE TITLE
SAPA public forum permissions

### ISSUE THREAD

**Issue by tutgreco** [saesrpg/saesrpg-web#32]
oi,
i am getting reports of applicants not being able to see our [public forum section](https://saesrpg.uk/category/184/application-section), also cadets are saying that they can view the [application archive](https://saesrpg.uk/category/185/application-archive) (which is supposed to be for [instructor group](https://saesrpg.uk/groups/sapa-instructors) only).

here's the request i initially made: https://github.com/saesrpg/saesrpg-web/issues/31
we are looking forwards to a fix on this issue, thank you in advance

**Comment by saesrpg** [comment]
Try now, any issues, reopen @tutgreco
