### ISSUE TITLE
PM draft clearing when maximizing chat window

### ISSUE THREAD

**Issue by tut98** [saesrpg/saesrpg-web#328]
When writing a Forum PM in normal size window, and then maximizing it leads to the draft getting cleared.
This is not the case when going from fullscreen to minimized chat mode.

**Comment by jonathdb93** [comment]
@tut98 This doesn't seem like an issue anymore, is this still relevant?

**Comment by tut98** [comment]
Yep it works fine, thanks for checking @jonathdb93
