### ISSUE TITLE
IAC forum mod rights

### ISSUE THREAD

**Issue by Dufabo** [saesrpg/saesrpg-web#33]
Greetings.I would like to request moderator rights for all iac forums :
https://saesrpg.uk/category/107/investarms-corporation
https://saesrpg.uk/category/205/recruitment
https://saesrpg.uk/category/206/members-area
https://saesrpg.uk/category/207/divisional-command

for following users :
https://saesrpg.uk/user/karma
https://saesrpg.uk/user/element
https://saesrpg.uk/user/reggi

**Comment by saesrpg** [comment]
This is now done, any issues, please re-open the ticket @Dufabo
