### ISSUE TITLE
Cuban Cars Forum Issiue

### ISSUE THREAD

**Issue by BlueSAES** [saesrpg/saesrpg-web#339]
People are not able to edit, make changes on their topics. We request them to have privileges to make changes on their topics, comments. 

https://saesrpg.uk/category/498/cuban-cars-activities

**Comment by jonathdb93** [comment]
Edit privileges have been granted to verified users, please verify and let me know if this issue still occurs!

**Comment by IamYoko** [comment]
This is working just fine now. Thanks!
