### ISSUE TITLE
Some requests about the new theme

### ISSUE THREAD

**Issue by FilexGH** [saesrpg/saesrpg-web#34]
* The search button dissepeared from the phone version
* Id like to see the quick reply thingy back too
* some buttons are breaking because of size or small tabulation space idk maybe that should be fixed

**Comment by saesrpg** [comment]
Quick reply is enabled again, will look at the rest soon

**Comment by saesrpg** [comment]
Ive adjusted the buttons and added the search button back on mobile menu.

If you still have issues with buttons, reopen this and add screenshots please.
