### ISSUE TITLE
LoungeVC Forums

### ISSUE THREAD

**Issue by BlueSAES** [saesrpg/saesrpg-web#340]
Give full access to following users on forums, (https://saesrpg.uk/category/137/lounge-vc) I should've have permissions but they seem to be fucked up.

https://saesrpg.uk/user/blue
https://saesrpg.uk/user/judyes

**Comment by jonathdb93** [comment]
Access should be sorted, Blue already seems to have all rights (besides create poll which I have now also granted)

**Comment by jonathdb93** [comment]
Question @BlueSAES , does this request also include all of the subcategories (Lounge VC HQ, Lounge Archive, Lounge Gang Wars & Lounge Race Wars) or only the main category (Lounge VC)?
