### ISSUE TITLE
SSB Level 1 forum rewards

### ISSUE THREAD

**Issue by blizzardOG99** [saesrpg/saesrpg-web#341]
Hello, I am blizzard, SSB's Leader
--

I would like to request a private forum section and private forum group

The private forum should contain the following topics:

https://saesrpg.uk/topic/30394/south-side-blazers
https://saesrpg.uk/topic/30395/south-side-blazers-media-archive

As for the forum's moderation rights, please give them to the following users:

https://saesrpg.uk/user/blizzard
https://saesrpg.uk/user/angrysandvich
https://saesrpg.uk/user/nobodyknows
https://saesrpg.uk/user/marso
https://saesrpg.uk/user/rykila
https://saesrpg.uk/user/rivals
https://saesrpg.uk/user/twenta

For the group ownership, please give it to me and I will take care of the rest.

Thank you.

**Comment by jonathdb93** [comment]
Could not find user [angrysandvich](https://saesrpg.uk/user/angrysandvich)

**Comment by blizzardOG99** [comment]
> Could not find user [angrysandvich](https://saesrpg.uk/user/angrysandvich)

https://saesrpg.uk/user/mellow he changed his nickname

**Comment by jonathdb93** [comment]
Group has been created:
- Group moderator permissions granted to blizzard
- Other HQ members have been added to group without moderator privileges (feel free to grant these to them as you please)
Categories have been created:
- SSB (https://saesrpg.uk/category/509/south-side-blazers) - Public
- SSB Private - Private to SSB members only
- Users mentioned have been given moderator privileges in both categories
- Topics have been moved to SSB category

Please verify and let me know if anything else is needed!

**Comment by blizzardOG99** [comment]
@jonathdb93 all good, thanks for it!
