### ISSUE TITLE
The Motor Heads - Moderators Changes

### ISSUE THREAD

**Issue by protonyt** [saesrpg/saesrpg-web#345]
*Greetings,*

I'd like to remove all moderators from **TMH**'s sub forum and add the following ones instead with all abilities to both public & private sections:

* **Proton:** https://saesrpg.uk/user/proton
* **Villain:** https://saesrpg.uk/user/villain
* **Taj:** https://saesrpg.uk/user/taj
* **JohnnyEnglish:** https://saesrpg.uk/user/johnnyenglish
* **Steven:** https://saesrpg.uk/user/steven
* **Killer:** https://saesrpg.uk/user/killer
* **Aoxy:** https://saesrpg.uk/user/aoxy
* **Rieeria:** https://saesrpg.uk/user/rieeria

***

**The Motor Heads' Sub Forum:** https://saesrpg.uk/category/173/the-motor-heads-tmh

**Comment by jonathdb93** [comment]
@protonyt 

- All moderators have been removed from the TMH subforums
- Hidden group "TMH Moderators" has been created, all mentioned users have been added as group moderator and this group has moderation rights across all subforums.

Please validate and reply here!
