### ISSUE TITLE
Royal Flush Moderation Update

### ISSUE THREAD

**Issue by KingNevs** [saesrpg/saesrpg-web#347]
Villain, Thamond and Shadow needs to be able to edit the "Main Topic" post which you can find on the following link:

https://saesrpg.uk/topic/25248/royal-flush?page=1

JukyPlatinium, Thamond, Villain, Shadow and Sharky needs to be able to edit all posts in our "Media Archive" which you can find on the following link:

https://saesrpg.uk/topic/25249/royal-flush-media-archive?page=1

**Comment by SAESKain** [comment]
Permissions are done per forum, not per topic. Please resubmit your request with this in mind and create a ticket on discord with the new git request
