### ISSUE TITLE
Name tags 

### ISSUE THREAD

**Issue by FilexGH** [saesrpg/saesrpg-web#36]
Well i wanna see the group tags back like old theme after names when you post

**Comment by saesrpg** [comment]
You mean just on mobile?

**Comment by FilexGH** [comment]
Just on mobile yes
Like i will show what i mean with a difference picture
![1](https://cdn.discordapp.com/attachments/512029434245545986/572492376715558922/Screenshot_20190429_193931.jpg)

As u see there is the group tag and number of posts/reputation

It would be cool if we have em back 

![2](https://cdn.discordapp.com/attachments/512029434245545986/572492376715558923/Screenshot_20190429_193852.jpg)

**Comment by saesrpg** [comment]
This will be added soon

**Comment by saesrpg** [comment]
This is now fixed.
