### ISSUE TITLE
Event topic bug ( theme related? )

### ISSUE THREAD

**Issue by boney420** [saesrpg/saesrpg-web#37]
When checking participants it does not allow me to scroll down to see who else is attending
https://i.gyazo.com/3a38ed3a2525516b2a1edeb59bbe15bb.png

Also the avatars are enormous: https://i.imgur.com/1IYsutr.jpg

**Comment by saesrpg** [comment]
Cheers, I'll look into it, probably just needs a bit of css fixing

**Comment by saesrpg** [comment]
Sorted
