### ISSUE TITLE
HQ's section In OC forums

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-web#4]
We'd like to have an HQs section In OverdoseCrime private forums here, https://saesrpg.uk/category/240/overdosecrime

Thank you.

**Comment by saesrpg** [comment]
This now done, please let me know the forum profiles of the people you want adding, so they can access it.

**Comment by Mrwann** [comment]
Elyes: https://saesrpg.uk/user/elyes
Hoodie: https://saesrpg.uk/user/hoodie
JohnnyEnglish: https://saesrpg.uk/user/johnnyenglish

**Comment by saesrpg** [comment]
This is now done
