### ISSUE TITLE
Cunning Stunts Forum Moderator Rights

### ISSUE THREAD

**Issue by RealCarter** [saesrpg/saesrpg-web#40]
Hello There,

We would like to request Moderator Rights for following members of Cunning Stunts

https://saesrpg.uk/user/pular
https://saesrpg.uk/user/garcia1999

Topics:
https://saesrpg.uk/category/163/cunning-stunts
https://saesrpg.uk/category/164/cunning-stunts-members
https://saesrpg.uk/category/165/cunning-stunts-hq
https://saesrpg.uk/category/218/archive

**Comment by saesrpg** [comment]
This is now done.
