### ISSUE TITLE
Cant open Spoilers

### ISSUE THREAD

**Issue by IEDaryl** [saesrpg/saesrpg-web#41]
Literally title, cannot open spoilers. I click spoiler and it just does nothing.

No idea why, have tried clearing cache and cookies but nada.

**Comment by saesrpg** [comment]
It's something to do with the plugin, I have reported it to the developer, it works if you visit the post via an internal link but not when you directly visit a URL.

Might be somehting to do with ajax or lazy loading

**Comment by saesrpg** [comment]
@IEDaryl this is now fixed
