### ISSUE TITLE
Cartel Da Sinaloa Level 1 Rewards 

### ISSUE THREAD

**Issue by Kalye07** [saesrpg/saesrpg-web#43]
Hello everyone, 

We would like to request our level 1 Rewards which are: 

1st: Infernus & Huntley as gang vehicles at color = #8a3f3f
2nd: A teamspeak channel 
3rd: A private forums and group for the gang  (the moderators=> @kayLe , @medai and @ElGrandeMaroki
)

Thank you all.

**Comment by saesrpg** [comment]
This is now done, you will need to request your in-game / teamspeak rewards via the gang issue tracker:
https://github.com/saesrpg/saesrpg-gang/issues repo
