### ISSUE TITLE
The Strike Team forum mod rights request and acces HQ forum

### ISSUE THREAD

**Issue by N-FUN** [saesrpg/saesrpg-web#44]
We would like to request the following:

Forum moderator rights for general forum:
Link to user: https://saesrpg.uk/user/aspect
Link to forum: https://saesrpg.uk/category/120/the-strike-team

Acces to HQ forum:
Link to user: https://saesrpg.uk/user/aspect
Link to forum: https://saesrpg.uk/category/287/commander-office

**Comment by saesrpg** [comment]
Done
