### ISSUE TITLE
Change topic author Rebels MC

### ISSUE THREAD

**Issue by Kare0015** [saesrpg/saesrpg-web#46]
I'd like to request a change of author of the following topics:

[Media archive](https://saesrpg.uk/topic/3179/rebels-mc-level-2?page=1)
[Application topic](https://saesrpg.uk/topic/3179/rebels-mc-level-2?page=1)

To my account so I can edit them as president: 
[Bas](https://saesrpg.uk/user/bas)

**Comment by saesrpg** [comment]
We cannot change the author of a topic at this moment in time, you will need to re-create the topics
