### ISSUE TITLE
Centrino: Mod rights forums

### ISSUE THREAD

**Issue by stayA9** [saesrpg/saesrpg-web#48]
Hello There SAES Dev's, I'd like to request Forums rights, Seems like now i'll use them , Need to work on it, thanks in advice.

personal Profile: https://saesrpg.uk/user/stay
Areas :
https://saesrpg.uk/category/104/taxi-el-centrino & Private forums category.

Salutes :)

**Comment by IEDaryl** [comment]
Terry being the leader of Centrino should make the request.

At a minimum you should get him to sign off on this request on this ticket

**Comment by stayA9** [comment]
Daryl yeah sure I'll get his letter down here :)

**Comment by boney420** [comment]
still waiting on confirmation of Terry get this done asap

**Comment by boney420** [comment]
closed, due to no response
