### ISSUE TITLE
SAM: Forums mod rights

### ISSUE THREAD

**Issue by Marko201** [saesrpg/saesrpg-web#51]
Hi
Requesting moderation access for [**JohnnyEnglish**](https://saesrpg.uk/user/johnnyenglish)
on both [1](https://saesrpg.uk/category/95/san-andreas-medics) and [2](https://saesrpg.uk/category/168/sam-members)

with viewing access to both [1](https://saesrpg.uk/category/169/sam-hq) and [2](https://saesrpg.uk/category/170/sam-applications-archive) 

Thanks

**Comment by saesrpg** [comment]
Done
