### ISSUE TITLE
San Andreas Studios Forum Request

### ISSUE THREAD

**Issue by Scorpyooooo** [saesrpg/saesrpg-web#53]
We have been told to request this by GMs so here is it.
First of all, i would like to request a forum group under the name "San Andreas Studios"
Also, we will need a public sub category in groups section with the name "San Andreas Studios", and inside of it 3 other sub forums : "SaS Private Area" visible only for the forum group members, "SaS HQ Area" and "SaS Archive" visible only for users with mod rights below
Mod rights on the whoel category should be given to the following  users:
https://saesrpg.uk/user/ganja
https://saesrpg.uk/user/karma
https://saesrpg.uk/user/colo
https://saesrpg.uk/user/scorpyo
https://saesrpg.uk/user/johnnyenglish

Finally, we need this topic moved to our category : https://saesrpg.uk/topic/6108/san-andreas-studios-media-archive/

 (Approval : https://discordapp.com/channels/229936715383439361/468783796750254100/584475332451631150 )

**Comment by saesrpg** [comment]
Done
