### ISSUE TITLE
SAI: Mod rights

### ISSUE THREAD

**Issue by Marko201** [saesrpg/saesrpg-web#55]
Hello, 

Would like to request moderation access for the following people:
1. **[Marko](https://saesrpg.uk/user/marko)**
2. **[Sam_](https://saesrpg.uk/user/sam_)**
3. **[iTsMe](https://saesrpg.uk/user/itsme)**
4. **[Dom](https://saesrpg.uk/user/doom)**
On the following links: [One](https://saesrpg.uk/category/96/san-andreas-interceptors), [Two](https://saesrpg.uk/category/151/patrol-bureau), and three is the Database requested below.

With SAI Leader, Ardron confirmation as shown [HERE](https://i.imgur.com/uNu7w7k.png)

____ 
Also, would be nice having a new sub_forum called "**SAI Database**" **[here](https://saesrpg.uk/category/96/san-andreas-interceptors)** that only people with mod access can view it.
___
Thanks in advance

**Comment by saesrpg** [comment]
@Marko201 this is now done.

**Comment by Marko201** [comment]
http://saesrpg.uk/category/151/patrol-bureau 
Still dont have moderation access on that link above
