### ISSUE TITLE
Black~Bullets -  Mod rights

### ISSUE THREAD

**Issue by iMatizZ** [saesrpg/saesrpg-web#57]
Heyo ! Me and A7md would like to have mod rights in B~B private forums .
**Links:**

- https://saesrpg.uk/category/210/black-bullets

- A7md's forum profile link: https://saesrpg.uk/user/a7md

- My forum profile link: https://saesrpg.uk/user/matizz

**Comment by boney420** [comment]
need confirmation of your leader(s)

**Comment by saesrpg** [comment]
@iMatizZ please see bone's note.

**Comment by iMatizZ** [comment]
It should be confirmed now :)

**Comment by saesrpg** [comment]
@iMatizZ where?

**Comment by iMatizZ** [comment]
ESO sent dm to Bone

**Comment by iMatizZ** [comment]
is it ok now ? or somethings missing ?

**Comment by boney420** [comment]
solved bishes
