### ISSUE TITLE
Requesting Moderator Perms for BES

### ISSUE THREAD

**Issue by adriano3756** [saesrpg/saesrpg-web#58]
Greetings, as I'm the director of this group. I would like to grant topic tools/mod permissions for wizax ,karma and faysal for BES forums.
https://saesrpg.uk/category/52/black-eagle-security

https://saesrpg.uk/user/karma
Wizax's account: https://saesrpg.uk/user/wizax
Faysal's account: https://saesrpg.uk/user/faysal

Thank you.

**Comment by saesrpg** [comment]
Done
