### ISSUE TITLE
css bug while scrolling on phone

### ISSUE THREAD

**Issue by boney420** [saesrpg/saesrpg-web#59]
https://cdn.discordapp.com/attachments/242393305302695936/591898156367740929/Schermafbeelding_20190622-095135.png

https://cdn.discordapp.com/attachments/242393305302695936/591898156367740928/Schermafbeelding_20190622-095139.png

**Comment by FilexGH** [comment]
Hmm the background

**Comment by saesrpg** [comment]
Will look into it
