### ISSUE TITLE
reopen case #55 "SAI forums"

### ISSUE THREAD

**Issue by Marko201** [saesrpg/saesrpg-web#60]
Hi again, idk if you can see replies to [closed cases](https://github.com/saesrpg/saesrpg-web/issues/55) so iam starting a new one. 

1. We still don't have moderation access on [Patrol Bureau ](https://saesrpg.uk/category/151/patrol-bureau)

2. Access for "[Marko](https://saesrpg.uk/user/marko)/[Sam_](https://saesrpg.uk/user/sam_)/[iTsMe](https://saesrpg.uk/user/itsme)/[Dom](https://saesrpg.uk/user/doom)" to view "Executive Staff" sub forum if it's present if not, would be great adding it as we used to have it back in old forums.

3. Idk if it's available or not but would be great to change [that icon](https://i.imgur.com/f5t1kNR.png) to [that logo](https://i.imgur.com/UMkzgG2.png) if possible

Thank you.

**Comment by tutgreco** [comment]
If you have ownership on the forum group, go into group administration and use the `change icon` to make changes

**Comment by Marko201** [comment]
> If you have ownership on the forum group, go into group administration and use the `change icon` to make changes

https://i.imgur.com/S69rN67.png

**Comment by Marko201** [comment]
Another quick thing, Edit button seems to be not an option on SAI forums so would be nice having it.

**Comment by IEDaryl** [comment]
This has been approved by SAI HQ.

**Comment by saesrpg** [comment]
This is now done @Marko201 @IEDaryl
