### ISSUE TITLE
Al - Munazama Forums Request.

### ISSUE THREAD

**Issue by ReggiGH** [saesrpg/saesrpg-web#61]
Hey, Id like to request the private forums for our group Al - Munazama. We have meet each requirement listed on the topic as stated below:

We have a fully detailed topic about the group role, members, application format etc.  
We have been active on the server for at least four months.
We have a media archive topic where the roleplays, events are documented.
We have completed 40 high quality roleplays.
Etc..

Main Forum Name: Al-Munazama - المنظمة

We would like to request 3 Sub forums for the moment listed below:

Rebels Hideout - (Members Only)
Application Archive - (Members Only)
Recruitment - (Public) 

I would like for the following people to get MOD rights to this forum:

https://saesrpg.uk/user/virusln
https://saesrpg.uk/user/blu%C3%A9
https://saesrpg.uk/user/adistar
https://saesrpg.uk/user/reggi
https://saesrpg.uk/user/harb

Forums Approved by GM: Nicusi
Thanks.

**Comment by ViRuSLN** [comment]
We also want this topic below to be moved to the main forum, thanks in advance.
Link:
https://saesrpg.uk/topic/1436/al-munazama-media-center

**Comment by saesrpg** [comment]
This is now done @ReggiGH 

@ViRuSLN the topic does not need to be moved as it's in the correct location for media.
