### ISSUE TITLE
Editing topic polls

### ISSUE THREAD

**Issue by tutgreco** [saesrpg/saesrpg-web#62]
Hello.

**Issue**: I have come accross of an issue, though not sure if intended or not.
If you're trying to edit your poll by adding an entirely new one, or changing contents, it won't be formatted as one, just raw text. Old one will stay regardless of what you do, and you can't change its code. (It's not available in the thread when editing).

**Request**: Being able to edit questions, title etc, thus resetting the poll votes, would be very helpful in case you missed something and not having to make a new thread.

Thank you very much :older_man:

**Comment by FilexGH** [comment]
+++++1

**Comment by saesrpg** [comment]
Report here @tutgreco : https://github.com/NodeBB/nodebb-plugin-poll

**Comment by tutgreco** [comment]
Looks like I wasn't the first one to issue a note on it. 
https://github.com/NodeBB/nodebb-plugin-poll/issues/42
from 3 years ago :rampage:
