### ISSUE TITLE
SAFD Forum's Subcategories

### ISSUE THREAD

**Issue by Ramos116** [saesrpg/saesrpg-web#65]
Can you please add 3 new subcategories below '' SAFD Members Area ''.(https://saesrpg.uk/category/158/san-andreas-fire-dept)

Name them:
- San Fierro District
- Los Santos District
- Las Venturas District

Moderator rights goes to: 
https://saesrpg.uk/user/laza
https://saesrpg.uk/user/ramos
https://saesrpg.uk/user/magnus
https://saesrpg.uk/user/buddler
https://saesrpg.uk/user/marko

For the request, I got a permission from SAFD Chief - Magnus.

**Comment by SAESKain** [comment]
I'm not convinced the group is even remotely active to justify the 15 mins I would spend doing this

**Comment by Ramos116** [comment]
Please, we're slowly getting up again. That thing would really be helpful to us, since we need our own seperated sections to keep things organized and not a mess.

**Comment by saesrpg** [comment]
@Ramos116 do you want them private or public?

**Comment by saesrpg** [comment]
Completed as per discord convo
