### ISSUE TITLE
Remove BBMC, WA and STF Forums group

### ISSUE THREAD

**Issue by Markus139** [saesrpg/saesrpg-web#66]
Remove these three forum groups since the organizations were closed and are officially dead.

**BBMC:**
https://saesrpg.uk/groups/the-blood-brothers-mc

**STF:**
https://saesrpg.uk/groups/special-task-force

**WA:**
https://saesrpg.uk/groups/wild-angels

**Comment by FilexGH** [comment]
Mean boi markyd
