### ISSUE TITLE
SAPD section mod rights

### ISSUE THREAD

**Issue by tutgreco** [saesrpg/saesrpg-web#68]
Hey, we would like to add mod rights on the [SAPD PC](https://saesrpg.uk/category/114/sapd-pc-qualified-officers) section for users [Sam](https://saesrpg.uk/user/sam_), [DROT](https://saesrpg.uk/user/drot), [Tut](https://saesrpg.uk/user/tut-greco) and [Sam-B](https://saesrpg.uk/user/sam-b)

:moistpepe:

**Comment by saesrpg** [comment]
Done
