### ISSUE TITLE
OB's Forum subcategories & Permissions

### ISSUE THREAD

**Issue by Ahren7413** [saesrpg/saesrpg-web#69]
Hello! I'd like to request HQ Permissions in OB Private forums (https://saesrpg.uk/topic/7654/outbreak-organization-roster that is the roster so you can check and my forum account: https://saesrpg.uk/user/licano). 
Also we'd like to request a new subcategory in the forum, visible for everyone, members and not members. It would be called "Recruitment" so we can organize all the applications in there. Thank you in advance and sorry for bothering.

**Comment by saesrpg** [comment]
Done.
