### ISSUE TITLE
Rights on AA pvt forums.

### ISSUE THREAD

**Issue by Ahren7413** [saesrpg/saesrpg-web#7]
Hello there! Sorry for bothering but since I'm the newest HQ in AA, seems like I'm the only one left without rights in the AA private forums. Would like to get them, if possible. A topic with the current AA roaster (there you can check my rank as HQ): https://saesrpg.uk/topic/4220/aa-roster and the link to my forum's profie: https://saesrpg.uk/user/licano .

Thanks for reading, sorry for bothering.

**Comment by saesrpg** [comment]
This is now done.
