### ISSUE TITLE
VeC Level 1 Rewards

### ISSUE THREAD

**Issue by Markus139** [saesrpg/saesrpg-web#71]
Request for the Level 1 rewards of **Vándalos de El Corona**
***
**Forum group named:** Vándalos de El Corona
**Administrative access:** https://saesrpg.uk/user/henry & https://saesrpg.uk/user/markus
***
Also we'd like to take the **Savanna** & **Burrito**. Savanna needs to be pained #b39f33 & Burrito needs to be black which I think is #000000. Also add NOS to both of them and Hydraulics to only the Savanna _(If the upgrades can't be done, no problem)_. Place them in the hood of El Corona to one of the houses owned by **Henry** or **CasuaL**.  **(SORTED)**
***
Gang fee will be paid by Markus or Henry.  **(SORTED)**

**Comment by saesrpg** [comment]
This is now done @Markus139
