### ISSUE TITLE
The Pirus - Level 1 Rewards

### ISSUE THREAD

**Issue by SoulFly44** [saesrpg/saesrpg-web#72]
Dear SAES staff;

Desired rewards;
**2 gang vehicles** ( Huntley - Stratum ) - ADDED
**Teamspeak3 channel.**
**A private forum for your gang:**
Private Forum Name: The Pirus
https://saesrpg.uk/user/soulfly
https://saesrpg.uk/user/fastyounq
https://saesrpg.uk/user/asgal

**Comment by saesrpg** [comment]
@SoulFly44 you need to make a separate issue for the gang rewards on the gang reward tracker, however, I will now do the forum changes.

**Comment by saesrpg** [comment]
@SoulFly44 The website changes are now complete.
