### ISSUE TITLE
Emergency Task Force reward requests Level 1

### ISSUE THREAD

**Issue by Vennelle** [saesrpg/saesrpg-web#73]
**Dear SAES staff,**

Hereby i would like to request the rewards for ETF's level 1 acceptance,

1] 2 Police LV cars placed at LVPD next to my donated police cars.
2] A private forum named ''Emergency Task Force'' with the group HQ - https://saesrpg.uk/user/vennelle & https://saesrpg.uk/user/antirug and i would like to have it set to private.
3] A TeamSpeak 3 channel called ''Emergency Task Force''

Thank you verry much for your time!

(5M acceptance fee has been paid to SAES>Kain)

**Kind regards,
Vennelle.**

**Comment by saesrpg** [comment]
@Vennelle you will need to make the in-game / ts rewards request on the https://github.com/saesrpg/saesrpg-gang/issues tracker if you haven't already, however, the forum changes will now be done.

**Comment by Vennelle** [comment]
> @Vennelle you will need to make the in-game / ts rewards request on the https://github.com/saesrpg/saesrpg-gang/issues tracker if you haven't already, however, the forum changes will now be done.

Yes i have already done that, first i also requested the forum there but Ikzelf sent me over here so i just copied and pasted everything over here.

Thank you!

**Comment by saesrpg** [comment]
@Vennelle this is now done
