### ISSUE TITLE
Clandestine Mob reward request

### ISSUE THREAD

**Issue by Noizi007** [saesrpg/saesrpg-web#75]
Hello , we heard that you need to request the gang forum in here , for that, we would like a Private Forum and group tag with the color #776017 under the name ' Clandestine Mob' and owner/admin permissions to : 
[https://saesrpg.uk/user/noisyboy](url)
[https://saesrpg.uk/user/jesse421](url)

**Comment by saesrpg** [comment]
This is now done @Noizi007
