### ISSUE TITLE
SAPA public forum can't be found by regular users

### ISSUE THREAD

**Issue by tutgreco** [saesrpg/saesrpg-web#76]
this is what they see:
https://cdn.discordapp.com/attachments/511197379232268356/606697629031596042/unknown.png

this is the section they're supposed to see: https://saesrpg.uk/category/184/application-section
while this section should remain private: https://saesrpg.uk/category/185/application-archive
and this is also a private section, should not be changed: https://saesrpg.uk/category/41/sapa

**Comment by SAESKain** [comment]
https://saesrpg.uk/category/41/sapa is the parent forum.

If the parent forum is hidden from the public then the rest will be as well.

**Comment by SAESKain** [comment]
I've moved the SAPA Application section outside of the SAPA category so it can be viewed by others. If this is not the solution you were seeking, find me on discord.
