### ISSUE TITLE
sub Forums

### ISSUE THREAD

**Issue by BASTBlade** [saesrpg/saesrpg-web#8]
Hi,I’m requesting 2 private forums and 1 archive for the raceTECH sub forum;
1. Archive
2. raceTECH Members
3. raceTECH HQ
And moderation rights, which I already requested at the previous report. 

Thank you,
Louis

https://oldbugs.saesrpg.uk/view.php?id=862

**Comment by saesrpg** [comment]
The raceTech forum is already for raceTECH members only, so I'll create the other two forums.

Still need a list of people who need access tho.
