### ISSUE TITLE
Modifications in OB's private forum.

### ISSUE THREAD

**Issue by Ahren7413** [saesrpg/saesrpg-web#81]
First: We'd like to have our banner as forum preview `https://i.imgur.com/E3tYAhs.png`. The current one is a default set by the forum `https://prnt.sc/oq9d14`

Second: For some reason the people posting in the Media archive `https://saesrpg.uk/topic/4130/outbreak-organization-media-archive/521` cannot edit their own reply, resulting in HQs having to edit every reply whenever it is uploaded not as intended.

Third: Also we'd like to remove `https://saesrpg.uk/user/terry` HQ's permissions since he's now no longer part of OB's HQ team.

Thank you in advance and sorry for bothering!

**Comment by SAESKain** [comment]
For some reason the banner isn't working, submit a smaller logo so we can try that instead in a new request.

Rest is done

**Comment by Velona77** [comment]
He means the sub-forums icon, the link below has a 128x128 square fit image, can you please try this?
https://i.ibb.co/Hh68Nbj/E3tYAhs.jpg
