### ISSUE TITLE
DE forum moderator

### ISSUE THREAD

**Issue by IG8820** [saesrpg/saesrpg-web#84]
As the title suggests, the following SAES profile requires moderation for the main DE forums. https://saesrpg.uk/user/ig8820

SAES>Bunny can be messaged for verification if necessary.

**Comment by saesrpg** [comment]
@IG8820 just the main root forum or subforums too? if subforums, which ones?

**Comment by Scorpyooooo** [comment]
@saesrpg just the main section, and remove Deu's moderation rights from any section in there, Sou's moderation right from Assault forum and Strong's moderator right from Naval forum.

**Comment by Scorpyooooo** [comment]
Please remove
JI6, Hesha, Royalty and Tayber from main forum mod
JI6, Hesha, Royalty from new recruit mod
JI6, Hesha, Royalty from airborne mod
JI6, Hesha, Royalty from assault mod
JI6, Hesha, Royalty from naval mod
JI6, Hesha, Royalty from archive mod
Tayber, Darius, Strong, xTrade, Deep from SF forum view/mod and add me & terry to view
