### ISSUE TITLE
Header or text size not functioning

### ISSUE THREAD

**Issue by BASTBlade** [saesrpg/saesrpg-web#9]
Making use of header formatting is not possible.

Make a post, write # hi or ### hi , it will write the hashtags literal rather than formatting "hi" as a header.

this used to be a feature, now it's gone or changed

https://oldbugs.saesrpg.uk/view.php?id=850

**Comment by saesrpg** [comment]
This works on both the full and quick editor for me, you need to make sure there is a space between the hashtag and the word.

Please let me know if you still have an issue and ill look at the settings in admin.

**Comment by saesrpg** [comment]
No change needed.
