### ISSUE TITLE
SAI mod rights

### ISSUE THREAD

**Issue by Marko201** [saesrpg/saesrpg-web#91]
Hey,
Would be nice to reset the SAI moderation access by removing all who can access it and give it to the following people on:
https://saesrpg.uk/category/96/san-andreas-interceptors
https://saesrpg.uk/category/151/patrol-bureau
https://saesrpg.uk/category/304/sai-database
https://saesrpg.uk/category/306/executive-staff   **(View access & Mod rights)**

to:

1- https://saesrpg.uk/user/ardron
2- https://saesrpg.uk/user/bas260
3- https://saesrpg.uk/user/henry
4- https://saesrpg.uk/user/marko
5- https://saesrpg.uk/user/dyamdouglas
6- https://saesrpg.uk/user/sam_
7- https://saesrpg.uk/user/absent
8- https://saesrpg.uk/user/itsme
9- https://saesrpg.uk/user/doom
_____
Last thing, people can't edit their posts somehow would be nice fixing that.
Edit: any new topic created along with some old ones doesn't have the edit option

Thank you.

**Comment by Ardron92** [comment]
I confirm
