### ISSUE TITLE
Requesting moderator rights

### ISSUE THREAD

**Issue by Ramos116** [saesrpg/saesrpg-web#94]
I'd like to request moderator rights here:

https://saesrpg.uk/category/162/safd-members-area
(And all 3 subcategories which are LV, LS, SF)

USERS:

https://saesrpg.uk/user/toolbox
https://saesrpg.uk/user/johnnyenglish
https://saesrpg.uk/user/bozi

**Comment by saesrpg** [comment]
@Ramos116 this is now done
