### ISSUE TITLE
Search is broken on SAES:RPG desktop in Google Chrome

### ISSUE THREAD

**Issue by DemienD** [saesrpg/saesrpg-web#95]
The command Ctrl+F is not working in Google Chrome for desktop. On mobile it is working as should. This probably has to do with the custom searchbox that used to be in place. I myself prefer Chrome's built in search over the one NodeBB had integrated because it just outperforms it.

![image](https://user-images.githubusercontent.com/15146566/63798298-1d4dba80-c90a-11e9-8dfc-a095ef554a78.png)
^ Note: also had this on a Mac device with latest Chrome

This issue has been here for a couple months only now bothered to report it. 

Edit:
I tried clearing my cache and cookies but that didn't fix it.

**Comment by DemienD** [comment]
Resolved by deleting all site data presets and whatsoever in Chrome

**Comment by saesrpg** [comment]
@DemienD You can also normally do ctrl+g to bypass the node one too.
