### ISSUE TITLE
ZIP forum mod rights

### ISSUE THREAD

**Issue by tilong** [saesrpg/saesrpg-web#99]
Hello i'd like to have Filex & Scorpyo added to ZIP group on forums moderatiln
Filex: https://saesrpg.uk/user/filex
Scorpyo: https://saesrpg.uk/user/scorpyo
ZIP Group: https://saesrpg.uk/groups/zip-planning-and-construction

Also i need to request a sub category with the name `Portfolios Database` [here](https://saesrpg.uk/category/147/zip-lounge), which can be seen by anyone in ZIP forum group.

Last but not least, please add a public sub category called `Recruitment` [here](https://saesrpg.uk/category/138/zip-planning-and-construction).

**Comment by boney420** [comment]
Sorted so far,

Only missing a list of who should be moderating the "recruitment" section

**Comment by FilexGH** [comment]
@boney420 both sections shall have Filex (me) & Scorpyo for both mentioned sections

**Comment by Scorpyooooo** [comment]
So far me and Filex arent added on all sub forums as mods, also people cant edit their posts/topics in the portoflios databse section

**Comment by boney420** [comment]
resolved you sousse
